// app/styles/reportante/welcomeStyles.ts
import { StyleSheet } from 'react-native';

export const welcomeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingVertical: 20,
    justifyContent: 'center',
  },
  header: {
    alignItems: 'center',
    marginBottom: 30,
  },
  logoContainer: {
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: '#2563EB',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  logo: {
    width: 100,
    height: 100,
    tintColor: '#FFFFFF',
  },
  roleBadge: {
    backgroundColor: '#F97316',
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderRadius: 25,
    marginTop: 10,
  },
  roleText: {
    fontFamily: 'Roboto_700Bold',
    fontSize: 18,
    color: '#FFFFFF',
    textAlign: 'center',
    letterSpacing: 1,
  },
  contentContainer: {
    backgroundColor: '#f8fafc',
    borderRadius: 16,
    padding: 24,
    marginBottom: 30,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  welcomeTitle: {
    fontFamily: 'Roboto_700Bold',
    fontSize: 22,
    color: '#2563EB',
    marginBottom: 15,
    textAlign: 'center',
  },
  welcomeText: {
    fontFamily: 'Montserrat_400Regular',
    fontSize: 16,
    color: '#475569',
    lineHeight: 24,
    marginBottom: 16,
    textAlign: 'justify',
  },
  highlightText: {
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 16,
    color: '#F97316',
  },
  missionContainer: {
    backgroundColor: '#dbeafe',
    borderRadius: 12,
    padding: 18,
    marginTop: 20,
    borderLeftWidth: 4,
    borderLeftColor: '#2563EB',
  },
  missionTitle: {
    fontFamily: 'Roboto_700Bold',
    fontSize: 18,
    color: '#1e40af',
    marginBottom: 8,
  },
  missionText: {
    fontFamily: 'Montserrat_400Regular',
    fontSize: 15,
    color: '#374151',
    lineHeight: 22,
  },
  continueButton: {
    backgroundColor: '#2563EB',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  continueButtonText: {
    fontFamily: 'Roboto_700Bold',
    fontSize: 18,
    color: '#FFFFFF',
  },
  footer: {
    marginTop: 25,
    alignItems: 'center',
  },
  footerText: {
    fontFamily: 'Roboto_400Regular',
    fontSize: 13,
    color: '#64748b',
    fontStyle: 'italic',
    textAlign: 'center',
  },
});